# Generated by Django 3.2.2 on 2021-05-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestorsProfile',
            new_name='InvestorProfile',
        ),
        migrations.AlterModelTable(
            name='investorprofile',
            table='investorprofile',
        ),
    ]
