# Generated by Django 3.2.2 on 2021-05-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_auto_20210512_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='pimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
