# Generated by Django 3.2.2 on 2021-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_alter_investorprofile_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='pimage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
