# Generated by Django 3.2.2 on 2021-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprenuer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreprenuerIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ideaname', models.CharField(max_length=100)),
                ('ideadesc', models.EmailField(max_length=100)),
                ('ideacat', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=400)),
                ('invmail', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='files/')),
            ],
            options={
                'db_table': 'entreprenuerideas',
            },
        ),
    ]
