# Generated by Django 3.2.2 on 2021-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprenuer', '0002_entreprenuerideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprenuerideas',
            name='ideadesc',
            field=models.CharField(max_length=100),
        ),
    ]
