# Generated by Django 3.2.2 on 2021-05-13 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprenuer', '0003_alter_entreprenuerideas_ideadesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprenuerideas',
            name='resume',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
